### ISSUE TITLE
Socks5 Connection rejection error

### ISSUE THREAD

**Issue by smetal1** [talmobi/tor-request#54]
I am getting the following error: 

{ Error: Socks5 proxy rejected connection - ConnectionRefused
    at SocksClient._closeSocket (/root/tor-test/node_modules/socks/build/client/socksclient.js:368:32)
    at SocksClient.handleSocks5FinalHandshakeResponse (/root/tor-test/node_modules/socks/build/client/socksclient.js:569:18)
    at SocksClient.processData (/root/tor-test/node_modules/socks/build/client/socksclient.js:310:22)
    at SocksClient.onDataReceived (/root/tor-test/node_modules/socks/build/client/socksclient.js:285:14)
    at Socket._onDataReceived (/root/tor-test/node_modules/socks/build/client/socksclient.js:201:47)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)

**Comment by talmobi** [comment]
Do you have the full error log? What are you trying to run?

That looks like the bottom snippet of an error ( missing logs on top ) when tor isn't running.

**Comment by talmobi** [comment]
@smetal1 Did you get it resolved?
