### ISSUE TITLE
Error: Socks5 proxy rejected connection - Failure

### ISSUE THREAD

**Issue by tomas-javurek** [talmobi/tor-request#71]
Hi, I'm getting this error on my CentOS 6 server:

```
Error: Socks5 proxy rejected connection - Failure
    at SocksClient._closeSocket (/node_modules/socks/build/client/socksclient.js:368:32)
    at SocksClient.handleSocks5FinalHandshakeResponse (/node_modules/socks/build/client/socksclient.js:569:18)
    at SocksClient.processData (/node_modules/socks/build/client/socksclient.js:310:22)
    at SocksClient.onDataReceived /node_modules/socks/build/client/socksclient.js:285:14)
    at Socket._onDataReceived (/node_modules/socks/build/client/socksclient.js:201:47)
    at Socket.emit (events.js:193:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:231:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:154:17)
```

cannot find any info all over. Any suggestion, what is going on?
Tor client seems to works well.

**Comment by talmobi** [comment]
@tomas-javurek I just now tested on OSX and Ubuntu -- they work fine.

Do you have a longer error log output?

What does the code you're running look like?

Is your tor client running on the default port 9050?

**Comment by talmobi** [comment]
@tomas-javurek There's a small chance your tor client is not up to date and will cause SOCKS5 related error with blank usernames, see: https://github.com/torproject/tor/pull/670

Try also updating your tor client if possible.

**Comment by tomas-javurek** [comment]
I've solved this issue. It was caused by an obsolete version of tor on my server system. The latest one is not in official repo anymore. The old version could not recognize a brand new (longer) onion links and marked them as invalid. The solution was to compile a latest version directly on my machine.

**Comment by talmobi** [comment]
@tomas-javurek thanks for the update~
